"""move license to dataset

Revision ID: 187634b7caa9
Revises: 5538d34fb11d
Create Date: 2013-06-25 12:57:14.882698

"""

# revision identifiers, used by Alembic.
revision = '187634b7caa9'
down_revision = '5538d34fb11d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('is_open', sa.Boolean(), nullable=True))
    op.add_column('dataset', sa.Column('license', sa.Unicode(), nullable=True))
    op.drop_column('resource', u'license')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column(u'license', sa.VARCHAR(), nullable=True))
    op.drop_column('dataset', 'license')
    op.drop_column('dataset', 'is_open')
    ### end Alembic commands ###
