"""Alter value_amount to decimal

Revision ID: 254ebd6e19c5
Revises: ce28b6ebf50
Create Date: 2013-04-10 12:10:31.206778

"""

# revision identifiers, used by Alembic.
revision = '254ebd6e19c5'
down_revision = '42f406c768f3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('budget', u'value_amount',
               existing_type=sa.INTEGER(),
               type_=sa.NUMERIC(),
               nullable=False)
    op.alter_column('transaction', u'value_amount',
               existing_type=sa.INTEGER(),
               type_=sa.NUMERIC(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('budget', u'value_amount',
               existing_type=sa.NUMERIC(),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('transaction', u'value_amount',
               existing_type=sa.NUMERIC(),
               type_=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###
