"""resource-license-version

Revision ID: 265060f037ba
Revises: 324dcec6842f
Create Date: 2013-06-19 15:52:56.147672

"""

# revision identifiers, used by Alembic.
revision = '265060f037ba'
down_revision = '324dcec6842f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('version', sa.Unicode(), nullable=True))
    op.add_column('resource', sa.Column('license', sa.Unicode(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'license')
    op.drop_column('resource', 'version')
    ### end Alembic commands ###
