"""add name/text to percentagemixin

Revision ID: 2a7ff47726c0
Revises: 283dd0bd3bf8
Create Date: 2013-05-20 13:30:42.978823

"""

# revision identifiers, used by Alembic.
revision = '2a7ff47726c0'
#down_revision = '283dd0bd3bf8'
down_revision = '2d2e2ae5c3e5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country_percentage', sa.Column('name', sa.Unicode(), nullable=True))
    op.add_column('region_percentage', sa.Column('name', sa.Unicode(), nullable=True))
    op.add_column('sector_percentage', sa.Column('text', sa.Unicode(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sector_percentage', 'text')
    op.drop_column('region_percentage', 'name')
    op.drop_column('country_percentage', 'name')
    ### end Alembic commands ###
