"""primary_key organisation table

Revision ID: 31c7d901bc0
Revises: 46223554578f
Create Date: 2013-06-13 23:52:04.593902

"""

# revision identifiers, used by Alembic.
revision = '31c7d901bc0'
down_revision = '46223554578f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('activity_reporting_org_ref_fkey', 'activity', type="foreignkey")
    op.drop_constraint('participation_organisation_ref_fkey', 'participation', type="foreignkey")
    op.drop_constraint('transaction_provider_org_ref_fkey', 'transaction', type="foreignkey")
    op.drop_constraint('transaction_receiver_org_ref_fkey', 'transaction', type="foreignkey")

    op.drop_constraint('organisation_pkey', 'organisation', type="primary")
    op.add_column('organisation', sa.Column('id', sa.Integer(), nullable=False, primary_key=True))
    op.create_primary_key('organisation_pkey', 'organisation', ['id'])

    op.add_column('activity', sa.Column('reporting_org_id', sa.Integer(), nullable=True))
    op.drop_column('activity', u'reporting_org_ref')
    op.add_column('participation', sa.Column('organisation_id', sa.Integer(), nullable=False))
    op.drop_column('participation', u'organisation_ref')
    op.add_column('transaction', sa.Column('provider_org_id', sa.Integer(), nullable=True))
    op.add_column('transaction', sa.Column('receiver_org_id', sa.Integer(), nullable=True))
    op.drop_column('transaction', u'provider_org_ref')
    op.drop_column('transaction', u'receiver_org_ref')

    op.create_foreign_key('activity_reporting_org_id_fkey', 'activity', 'organisation',
        ["reporting_org_id"], ["id"])
    op.create_foreign_key('participation_organisation_id_fkey', 'participation', 'organisation',
        ["organisation_id"], ["id"])

    op.create_foreign_key('transaction_provider_org_id_fkey', 'transaction', 'organisation',
        ["provider_org_id"], ["id"])

    op.create_foreign_key('transaction_receiver_org_id_fkey', 'transaction', 'organisation',
        ["receiver_org_id"], ["id"])
    op.create_unique_constraint("organisation_ref_name_type_key", "organisation", 
        ["ref", "name", "type"])
    
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('organisation_ref_name_type_key', 'organisation')

    op.drop_constraint('activity_reporting_org_id_fkey', 'activity', type="foreignkey")
    op.drop_constraint('participation_organisation_id_fkey', 'participation', type="foreignkey")
    op.drop_constraint('transaction_provider_org_id_fkey', 'transaction', type="foreignkey")
    op.drop_constraint('transaction_receiver_org_id_fkey', 'transaction', type="foreignkey")


    op.add_column('transaction', sa.Column(u'receiver_org_ref', sa.VARCHAR(), nullable=True))
    op.add_column('transaction', sa.Column(u'provider_org_ref', sa.VARCHAR(), nullable=True))
    op.drop_column('transaction', 'receiver_org_id')
    op.drop_column('transaction', 'provider_org_id')
    op.add_column('participation', sa.Column(u'organisation_ref', sa.VARCHAR(), nullable=False))
    op.drop_column('participation', 'organisation_id')
    op.add_column('activity', sa.Column(u'reporting_org_ref', sa.VARCHAR(), nullable=False))
    op.drop_column('activity', 'reporting_org_id')


    op.drop_constraint('organisation_pkey', 'organisation', type="primary")
    op.drop_column('organisation', 'id')
    op.create_primary_key('organisation_pkey', 'organisation', ['ref'])

    op.create_foreign_key('activity_reporting_org_ref_fkey', 'activity', 'organisation',
        ["reporting_org_ref"], ["ref"])
    op.create_foreign_key('participation_organisation_ref_fkey', 'participation', 'organisation',
        ["organisation_ref"], ["ref"])

    op.create_foreign_key('transaction_provider_org_ref_fkey', 'transaction', 'organisation',
        ["provider_org_ref"], ["ref"])

    op.create_foreign_key('transaction_receiver_org_ref_fkey', 'transaction', 'organisation',
        ["receiver_org_ref"], ["ref"])

    ### end Alembic commands ###
