"""Add log table

Revision ID: 31d3dc10e996
Revises: 454db9beed02
Create Date: 2013-04-03 11:12:35.294125

"""

# revision identifiers, used by Alembic.
revision = '31d3dc10e996'
down_revision = '454db9beed02'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logger', sa.String(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('trace', sa.String(), nullable=True),
    sa.Column('msg', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log')
    ### end Alembic commands ###
