"""policy-maker null

Revision ID: 324dcec6842f
Revises: 5873c078fd7f
Create Date: 2013-06-18 18:56:39.380860

"""

# revision identifiers, used by Alembic.
revision = '324dcec6842f'
down_revision = '5873c078fd7f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('policy_marker', u'code',
               existing_type=postgresql.ENUM(u'1', u'3', u'2', u'5', u'4', u'7', u'6', u'8', name=u'ck_policy_marker'),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('policy_marker', u'code',
               existing_type=postgresql.ENUM(u'1', u'3', u'2', u'5', u'4', u'7', u'6', u'8', name=u'ck_policy_marker'),
               nullable=False)
    ### end Alembic commands ###
