"""add related_activity and policy_marker

Revision ID: 35c85c5bfcb2
Revises: 2a7ff47726c0
Create Date: 2013-05-21 15:58:17.345953

"""

# revision identifiers, used by Alembic.
revision = '35c85c5bfcb2'
down_revision = '2a7ff47726c0'

from alembic import op
import sqlalchemy as sa
from iatilib import codelists

policy_marker_type = codelists.PolicyMarker.db_type().impl

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #policy_marker_type.create(bind=op.get_bind(), checkfirst=True)

    op.create_table('policy_marker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Unicode(), nullable=False),
    sa.Column('code', codelists.PolicyMarker.db_type(), nullable=False),
    sa.Column('text', sa.Unicode(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.iati_identifier'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('related_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Unicode(), nullable=False),
    sa.Column('ref', sa.Unicode(), nullable=False),
    sa.Column('text', sa.Unicode(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.iati_identifier'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('related_activity')
    op.drop_table('policy_marker')
    policy_marker_type.drop(bind=op.get_bind(), checkfirst=False)
    ### end Alembic commands ###
