"""Add transaction fields

Revision ID: 3dd506d98d0
Revises: ce28b6ebf50
Create Date: 2013-04-11 16:08:27.464159

"""

# revision identifiers, used by Alembic.
revision = '3dd506d98d0'
down_revision = 'ce28b6ebf50'

from alembic import op
import sqlalchemy as sa
from iatilib import codelists

aid_type = codelists.AidType.db_type().impl
tied_status = codelists.TiedStatus.db_type().impl
finance_type = codelists.FinanceType.db_type().impl
flow_type = codelists.FlowType.db_type().impl
disbursement = codelists.DisbursementChannel.db_type().impl

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('budget', u'value_amount', existing_type=sa.INTEGER(), 
                    type_=sa.NUMERIC(), nullable=False)

    op.add_column('transaction',
                    sa.Column('description', sa.Unicode(), nullable=True))
    op.add_column('transaction', sa.Column('receiver_org_activity_id',
                   sa.Unicode(), nullable=True))
    op.add_column('transaction', sa.Column('receiver_org_ref', sa.Unicode(),
                   sa.ForeignKey('organisation.ref'), nullable=True))
    op.add_column('transaction', sa.Column('receiver_org_text', sa.Unicode(),
                   nullable=True))
    op.alter_column('transaction', 'value_amount', existing_type=sa.INTEGER(),
                    type_=sa.NUMERIC(), nullable=False)
    op.add_column('transaction', sa.Column('provider_org_activity_id',
                   sa.Unicode(), nullable=True))
    op.add_column('transaction', sa.Column('provider_org_ref', sa.Unicode(),
                   sa.ForeignKey('organisation.ref'), nullable=True))
    op.add_column('transaction', sa.Column('provider_org_text',
                   sa.Unicode(), nullable=True))
    op.add_column('transaction', sa.Column('ref', sa.Unicode(), nullable=True))

    aid_type.create(bind=op.get_bind(), checkfirst=True)
    op.add_column(
            'transaction', 
            sa.Column('aid_type', codelists.AidType.db_type(), nullable=True)
    )

    tied_status.create(bind=op.get_bind(), checkfirst=True)
    op.add_column(
            'transaction',
            sa.Column(
                'tied_status',
                codelists.TiedStatus.db_type(),
                nullable=True
            )
    )

    finance_type.create(bind=op.get_bind(), checkfirst=True)
    op.add_column(
            'transaction',
            sa.Column(
                'finance_type',
                codelists.FinanceType.db_type(),
                nullable=True
            )
    )

    flow_type.create(bind=op.get_bind(), checkfirst=True)
    op.add_column(
            'transaction',
            sa.Column('flow_type', codelists.FlowType.db_type(), nullable=True)
    )

    disbursement.create(bind=op.get_bind(), checkfirst=True)
    op.add_column(
            'transaction',
            sa.Column(
                'disbursement_channel',
                codelists.DisbursementChannel.db_type(),
                nullable=True
            )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'disbursement_channel')
    op.drop_column('transaction', 'flow_type')
    op.drop_column('transaction', 'finance_type')
    op.drop_column('transaction', 'tied_status')
    op.drop_column('transaction', 'aid_type')
    op.drop_column('transaction', 'ref')
    op.drop_column('transaction', 'provider_org_text')
    op.drop_column('transaction', 'provider_org_ref')
    op.drop_column('transaction', 'provider_org_activity_id')
    op.drop_column('transaction', 'receiver_org_text')
    op.drop_column('transaction', 'receiver_org_ref')
    op.drop_column('transaction', 'receiver_org_activity_id')
    op.alter_column('budget', u'value_amount',
               existing_type=sa.NUMERIC(),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('transaction', u'value_amount',
               existing_type=sa.NUMERIC(),
               type_=sa.INTEGER(),
               nullable=False)
    op.drop_column('transaction', 'description')
    aid_type.drop(bind=op.get_bind())
    tied_status.drop(bind=op.get_bind())
    flow_type.drop(bind=op.get_bind())
    finance_type.drop(bind=op.get_bind())
    disbursement.drop(bind=op.get_bind())
    finance_type.drop(bind=op.get_bind())
    ### end Alembic commands ###
