"""country code nullable

Revision ID: 3feaa6f7b026
Revises: 265060f037ba
Create Date: 2013-06-24 10:46:43.015709

"""

# revision identifiers, used by Alembic.
revision = '3feaa6f7b026'
down_revision = '265060f037ba'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('country_percentage', u'country',
               existing_type=postgresql.ENUM(u'EH', u'TW', u'JP', u'EC', u'EE', u'EG', u'ZA', u'ZM', u'ER', u'ES', u'ET', u'MP', u'MQ', u'MR', u'MS', u'MT', u'MU', u'MV', u'MW', u'MX', u'MY', u'MZ', u'FI', u'MA', u'ZW', u'MC', u'MD', u'ME', u'MF', u'MG', u'MH', u'MK', u'ML', u'MM', u'MN', u'MO', u'DK', u'UY', u'UZ', u'DO', u'DM', u'US', u'DE', u'DZ', u'UM', u'UA', u'UG', u'LS', u'LR', u'LV', u'LU', u'LT', u'LY', u'HR', u'LC', u'LB', u'LA', u'AG', u'LK', u'LI', u'HU', u'GN', u'TZ', u'GL', u'PL', u'GH', u'GI', u'GF', u'TR', u'GD', u'GE', u'GB', u'TV', u'TT', u'TK', u'TJ', u'TH', u'TO', u'TN', u'TM', u'GY', u'TC', u'GW', u'GT', u'GU', u'TG', u'TF', u'GP', u'TD', u'HK', u'OM', u'JO', u'FR', u'WS', u'YE', u'WF', u'FK', u'FJ', u'FM', u'FO', u'VA', u'VC', u'NZ', u'VE', u'VG', u'VI', u'NP', u'NR', u'NU', u'VN', u'NI', u'VU', u'NL', u'NO', u'NA', u'NC', u'NE', u'NG', u'NF', u'AT', u'AU', u'AW', u'AQ', u'AR', u'AS', u'AX', u'AZ', u'AD', u'AE', u'AF', u'GM', u'AL', u'AM', u'AN', u'AO', u'AI', u'GR', u'QA', u'IT', u'KE', u'IQ', u'IR', u'IS', u'IL', u'IM', u'IN', u'IO', u'GG', u'ID', u'IE', u'KI', u'KN', u'CU', u'YT', u'GA', u'PG', u'PF', u'PE', u'PA', u'PN', u'PM', u'HT', u'PK', u'KP', u'PH', u'PW', u'HN', u'HM', u'PT', u'PS', u'PR', u'PY', u'CO', u'CZ', u'CX', u'CY', u'KG', u'DJ', u'CR', u'KH', u'TL', u'CV', u'CW', u'KM', u'KR', u'CK', u'CH', u'CI', u'CN', u'KW', u'CL', u'CM', u'KZ', u'CC', u'CA', u'CF', u'CG', u'CD', u'SJ', u'SK', u'SH', u'SI', u'SN', u'SO', u'SL', u'SM', u'SB', u'SC', u'SA', u'KY', u'SG', u'SD', u'SE', u'SZ', u'SX', u'SY', u'GS', u'SR', u'SS', u'GQ', u'SV', u'ST', u'JE', u'BY', u'BZ', u'JM', u'BT', u'BW', u'BV', u'BQ', u'BS', u'BR', u'BM', u'BL', u'BO', u'BN', u'BI', u'BH', u'BJ', u'BE', u'BD', u'BG', u'BF', u'BA', u'BB', u'RO', u'RE', u'RU', u'RW', u'RS', name=u'ck_country'),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('country_percentage', u'country',
               existing_type=postgresql.ENUM(u'EH', u'TW', u'JP', u'EC', u'EE', u'EG', u'ZA', u'ZM', u'ER', u'ES', u'ET', u'MP', u'MQ', u'MR', u'MS', u'MT', u'MU', u'MV', u'MW', u'MX', u'MY', u'MZ', u'FI', u'MA', u'ZW', u'MC', u'MD', u'ME', u'MF', u'MG', u'MH', u'MK', u'ML', u'MM', u'MN', u'MO', u'DK', u'UY', u'UZ', u'DO', u'DM', u'US', u'DE', u'DZ', u'UM', u'UA', u'UG', u'LS', u'LR', u'LV', u'LU', u'LT', u'LY', u'HR', u'LC', u'LB', u'LA', u'AG', u'LK', u'LI', u'HU', u'GN', u'TZ', u'GL', u'PL', u'GH', u'GI', u'GF', u'TR', u'GD', u'GE', u'GB', u'TV', u'TT', u'TK', u'TJ', u'TH', u'TO', u'TN', u'TM', u'GY', u'TC', u'GW', u'GT', u'GU', u'TG', u'TF', u'GP', u'TD', u'HK', u'OM', u'JO', u'FR', u'WS', u'YE', u'WF', u'FK', u'FJ', u'FM', u'FO', u'VA', u'VC', u'NZ', u'VE', u'VG', u'VI', u'NP', u'NR', u'NU', u'VN', u'NI', u'VU', u'NL', u'NO', u'NA', u'NC', u'NE', u'NG', u'NF', u'AT', u'AU', u'AW', u'AQ', u'AR', u'AS', u'AX', u'AZ', u'AD', u'AE', u'AF', u'GM', u'AL', u'AM', u'AN', u'AO', u'AI', u'GR', u'QA', u'IT', u'KE', u'IQ', u'IR', u'IS', u'IL', u'IM', u'IN', u'IO', u'GG', u'ID', u'IE', u'KI', u'KN', u'CU', u'YT', u'GA', u'PG', u'PF', u'PE', u'PA', u'PN', u'PM', u'HT', u'PK', u'KP', u'PH', u'PW', u'HN', u'HM', u'PT', u'PS', u'PR', u'PY', u'CO', u'CZ', u'CX', u'CY', u'KG', u'DJ', u'CR', u'KH', u'TL', u'CV', u'CW', u'KM', u'KR', u'CK', u'CH', u'CI', u'CN', u'KW', u'CL', u'CM', u'KZ', u'CC', u'CA', u'CF', u'CG', u'CD', u'SJ', u'SK', u'SH', u'SI', u'SN', u'SO', u'SL', u'SM', u'SB', u'SC', u'SA', u'KY', u'SG', u'SD', u'SE', u'SZ', u'SX', u'SY', u'GS', u'SR', u'SS', u'GQ', u'SV', u'ST', u'JE', u'BY', u'BZ', u'JM', u'BT', u'BW', u'BV', u'BQ', u'BS', u'BR', u'BM', u'BL', u'BO', u'BN', u'BI', u'BH', u'BJ', u'BE', u'BD', u'BG', u'BF', u'BA', u'BB', u'RO', u'RE', u'RU', u'RW', u'RS', name=u'ck_country'),
               nullable=False)
    ### end Alembic commands ###
