"""add ref to Transaction table

Revision ID: 42f406c768f3
Revises: 454db9beed02
Create Date: 2013-04-04 17:46:36.362765

"""

# revision identifiers, used by Alembic.
revision = '42f406c768f3'
down_revision = 'ce28b6ebf50'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('ref', sa.Unicode(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'ref')
    ### end Alembic commands ###
