"""Add provider_org-activity

Revision ID: 51c1761d9fe9
Revises: bbf2dfad4a4
Create Date: 2013-04-11 14:18:13.231975

"""

# revision identifiers, used by Alembic.
revision = '51c1761d9fe9'
down_revision = 'bbf2dfad4a4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('provider_org_activity_id', sa.Unicode(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'provider_org_activity_id')
    ### end Alembic commands ###
