"""activity_last_change_datetime

Revision ID: 5538d34fb11d
Revises: 3feaa6f7b026
Create Date: 2013-06-25 11:03:17.332937

"""

# revision identifiers, used by Alembic.
revision = '5538d34fb11d'
down_revision = '3feaa6f7b026'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('last_change_datetime', sa.DateTime(), nullable=False,
        server_default=sa.func.now()))
    op.alter_column('activity', 'last_updated_datetime', type_=sa.DateTime())
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity', 'last_change_datetime')
    op.alter_column('activity', 'last_updated_datetime', type_=sa.Date())
    ### end Alembic commands ###
