"""make fields nullable

Revision ID: 5873c078fd7f
Revises: 31c7d901bc0
Create Date: 2013-06-18 15:05:29.798352

"""

# revision identifiers, used by Alembic.
revision = '5873c078fd7f'
down_revision = '31c7d901bc0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('budget', u'value_amount',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('organisation', u'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('transaction', u'value_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('transaction', u'value_currency',
               existing_type=postgresql.ENUM(u'DZD', u'NAD', u'QAR', u'EGP', u'BOV', u'BMD', u'PAB', u'COU', u'BOB', u'DKK', u'BWP', u'LBP', u'TZS', u'VND', u'AOA', u'KHR', u'GHS', u'KYD', u'LYD', u'UAH', u'JOD', u'AWG', u'SAR', u'EUR', u'HKD', u'CHF', u'GIP', u'BYR', u'CDF', u'BAM', u'MRO', u'BGN', u'HRK', u'DJF', u'THB', u'XAF', u'BND', u'VUV', u'UYU', u'NIO', u'LAK', u'SYP', u'MAD', u'UYI', u'MZN', u'TTD', u'ZAR', u'NPR', u'ZWL', u'BTN', u'NGN', u'CRC', u'AED', u'EEK', u'MWK', u'LKR', u'PKR', u'HUF', u'SZL', u'LSL', u'MNT', u'AMD', u'UGX', u'JMD', u'GEL', u'SHP', u'AFN', u'SBD', u'KPW', u'GNF', u'MKD', u'TRY', u'BDT', u'YER', u'HTG', u'SLL', u'MGA', u'PHP', u'LRD', u'XCD', u'NOK', u'MXV', u'MOP', u'INR', u'MXN', u'CZK', u'TJS', u'PYG', u'KMF', u'MYR', u'TMT', u'MUR', u'IDR', u'HNL', u'XPF', u'FJD', u'ETB', u'PEN', u'BZD', u'ILS', u'DOP', u'TWD', u'MDL', u'BSD', u'SEK', u'ZMK', u'MVR', u'AUD', u'SRD', u'CUP', u'CLF', u'BBD', u'KRW', u'GMD', u'VEF', u'GTQ', u'ANG', u'CUC', u'CLP', u'LTL', u'ALL', u'RWF', u'KZT', u'RUB', u'ISK', u'OMR', u'BRL', u'MMK', u'PLN', u'KES', u'SVC', u'USD', u'GBP', u'AZN', u'USN', u'TOP', u'COP', u'USS', u'WST', u'IQD', u'ERN', u'CVE', u'SCR', u'CAD', u'GYD', u'KWD', u'BIF', u'PGK', u'SOS', u'SGD', u'UZS', u'STD', u'IRR', u'CNY', u'XOF', u'TND', u'NZD', u'FKP', u'LVL', u'KGS', u'ARS', u'RON', u'RSD', u'BHD', u'JPY', u'SDG', name=u'ck_currency'),
               nullable=True)
    op.alter_column('transaction', u'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('transaction', u'value_amount',
               existing_type=sa.NUMERIC(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', u'value_amount',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('transaction', u'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('transaction', u'value_currency',
               existing_type=postgresql.ENUM(u'DZD', u'NAD', u'QAR', u'EGP', u'BOV', u'BMD', u'PAB', u'COU', u'BOB', u'DKK', u'BWP', u'LBP', u'TZS', u'VND', u'AOA', u'KHR', u'GHS', u'KYD', u'LYD', u'UAH', u'JOD', u'AWG', u'SAR', u'EUR', u'HKD', u'CHF', u'GIP', u'BYR', u'CDF', u'BAM', u'MRO', u'BGN', u'HRK', u'DJF', u'THB', u'XAF', u'BND', u'VUV', u'UYU', u'NIO', u'LAK', u'SYP', u'MAD', u'UYI', u'MZN', u'TTD', u'ZAR', u'NPR', u'ZWL', u'BTN', u'NGN', u'CRC', u'AED', u'EEK', u'MWK', u'LKR', u'PKR', u'HUF', u'SZL', u'LSL', u'MNT', u'AMD', u'UGX', u'JMD', u'GEL', u'SHP', u'AFN', u'SBD', u'KPW', u'GNF', u'MKD', u'TRY', u'BDT', u'YER', u'HTG', u'SLL', u'MGA', u'PHP', u'LRD', u'XCD', u'NOK', u'MXV', u'MOP', u'INR', u'MXN', u'CZK', u'TJS', u'PYG', u'KMF', u'MYR', u'TMT', u'MUR', u'IDR', u'HNL', u'XPF', u'FJD', u'ETB', u'PEN', u'BZD', u'ILS', u'DOP', u'TWD', u'MDL', u'BSD', u'SEK', u'ZMK', u'MVR', u'AUD', u'SRD', u'CUP', u'CLF', u'BBD', u'KRW', u'GMD', u'VEF', u'GTQ', u'ANG', u'CUC', u'CLP', u'LTL', u'ALL', u'RWF', u'KZT', u'RUB', u'ISK', u'OMR', u'BRL', u'MMK', u'PLN', u'KES', u'SVC', u'USD', u'GBP', u'AZN', u'USN', u'TOP', u'COP', u'USS', u'WST', u'IQD', u'ERN', u'CVE', u'SCR', u'CAD', u'GYD', u'KWD', u'BIF', u'PGK', u'SOS', u'SGD', u'UZS', u'STD', u'IRR', u'CNY', u'XOF', u'TND', u'NZD', u'FKP', u'LVL', u'KGS', u'ARS', u'RON', u'RSD', u'BHD', u'JPY', u'SDG', name=u'ck_currency'),
               nullable=False)
    op.alter_column('transaction', u'value_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('organisation', u'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('budget', u'value_amount',
               existing_type=sa.NUMERIC(),
               nullable=False)
    ### end Alembic commands ###
