"""Add provider_org to transaction

Revision ID: bbf2dfad4a4
Revises: 42f406c768f3
Create Date: 2013-04-05 16:03:34.648044

"""

# revision identifiers, used by Alembic.
revision = 'bbf2dfad4a4'
down_revision = '254ebd6e19c5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('providing_org_ref', sa.Unicode(),
                   sa.ForeignKey('organisation.ref'), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'providing_org_ref')
    ### end Alembic commands ###
