"""add cols to activity

Revision ID: f155ce1c832
Revises: 385fd5385e36
Create Date: 2013-05-29 15:00:25.440443

"""

# revision identifiers, used by Alembic.
revision = 'f155ce1c832'
down_revision = '385fd5385e36'

from alembic import op
import sqlalchemy as sa
from iatilib import codelists

aid_type = codelists.AidType.db_type()
tied_status = codelists.TiedStatus.db_type()
finance_type = codelists.FinanceType.db_type()
flow_type = codelists.FlowType.db_type()

hierarchy = codelists.RelatedActivityType.db_type()
language = codelists.Language.db_type()
activity_status = codelists.ActivityStatus.db_type()
collaboration_type = codelists.CollaborationType.db_type()


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('default_tied_status', tied_status, nullable=True))
    op.add_column('activity', sa.Column('default_flow_type', flow_type, nullable=True))

    activity_status.impl.create(bind=op.get_bind(), checkfirst=True)
    op.add_column('activity', sa.Column('activity_status', activity_status, nullable=True))

    hierarchy.impl.create(bind=op.get_bind(), checkfirst=True)
    op.add_column('activity', sa.Column('hierarchy', hierarchy, nullable=True))
    op.add_column('activity', sa.Column('default_finance_type', finance_type, nullable=True))

    language.impl.create(bind=op.get_bind(), checkfirst=True)
    op.add_column('activity', sa.Column('default_language', language, nullable=True))
    op.add_column('activity', sa.Column('last_updated_datetime', sa.Date(), nullable=True))
    op.add_column('activity', sa.Column('default_aid_type', aid_type, nullable=True))

    collaboration_type.impl.create(bind=op.get_bind(), checkfirst=True)
    op.add_column('activity', sa.Column('collaboration_type', collaboration_type, nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity', 'collaboration_type')
    op.drop_column('activity', 'default_aid_type')
    op.drop_column('activity', 'last_updated_datetime')
    op.drop_column('activity', 'default_language')
    op.drop_column('activity', 'default_finance_type')
    op.drop_column('activity', 'hierarchy')
    op.drop_column('activity', 'activity_status')
    op.drop_column('activity', 'default_flow_type')
    op.drop_column('activity', 'default_tied_status')

    activity_status.impl.drop(bind=op.get_bind())
    language.impl.drop(bind=op.get_bind())
    collaboration_type.impl.drop(bind=op.get_bind())
    ### end Alembic commands ###
