from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
from sqlalchemy import Column,Integer,DateTime,Float,ForeignKey,UnicodeText,Boolean
from . import engine
from parser import _nav, _parse_float, _parse_int, _parse_datetime, _parse_boolean

Base = declarative_base()

class IndexedResource(Base):
    __tablename__ = 'indexed_resource'
    id = Column(UnicodeText, primary_key=True)
    url = Column(UnicodeText)
    last_modified = Column(DateTime)
    state = Column(Integer)
    ckan_url = Column(UnicodeText)
    xml_blobs = relationship("RawXmlBlob",cascade="all")
    logerrors = relationship("LogError",cascade="all")

class RawXmlBlob(Base):
    __tablename__ = 'raw_xml_blob'
    parent_id = Column(UnicodeText, ForeignKey('indexed_resource.id'), nullable=False)
    id = Column(Integer, primary_key=True)
    raw_xml = Column(UnicodeText)
    parsed = Column(Boolean)
    activity = relationship("Activity",cascade="all",uselist=False)

class LogError(Base):
    __tablename__ = 'logerror'
    id = Column(Integer, primary_key=True)
    parent_id = Column(UnicodeText, ForeignKey('indexed_resource.id'), nullable=False)
    level = Column(Integer)
    text = Column(UnicodeText)

class CodelistSector(Base):
    __tablename__ = 'codelist_sector'
    code = Column(Integer, primary_key=True)
    name = Column(UnicodeText)
    description = Column(UnicodeText)
    category = Column(Integer)
    category_name = Column(UnicodeText)
    category_description = Column(UnicodeText)

# =============================================================
# ========   Everything below is code-generated!   ============
# ========   See /spec for how it's made.          ============
# =============================================================
# ==  eg. (1) delete everything below                        ==
# ==      (2) put your cursor down there                     ==
# ==      (3) execute vim command:                           ==
# ==          :r ! python spec/codegen.py                    ==
# =============================================================


#######
### Autogenerated models for model.py created on 2013-02-11 23:54:35.062397
#######

class Activity(Base):
    __tablename__ = 'activity'
    id = Column(Integer, primary_key=True)
    transaction = relationship("Transaction",cascade="all")
    sector = relationship("Sector",cascade="all")
    participatingorg = relationship("ParticipatingOrg",cascade="all")
    contactinfo = relationship("ContactInfo",cascade="all")
    activitydate = relationship("ActivityDate",cascade="all")
    parent_id = Column(Integer, ForeignKey('raw_xml_blob.id'), nullable=False)
    version = Column(Float)	# @version
    last_updated_datetime = Column(DateTime)	# @last-updated-datetime
    lang = Column(UnicodeText)	# @xml:lang
    default_currency = Column(UnicodeText)	# @default-currency
    hierarchy = Column(Float)	# @hierarchy
    linked_data_uri = Column(UnicodeText)	# @linked-data-uri
    activity_website__text = Column(UnicodeText)	# activity-website/text()
    reporting_org__text = Column(UnicodeText)	# reporting-org/text()
    reporting_org__ref = Column(UnicodeText)	# reporting-org/@ref
    reporting_org__type = Column(UnicodeText)	# reporting-org/@type
    reporting_org__lang = Column(UnicodeText)	# reporting-org/@xml:lang
    recipient_country__text = Column(UnicodeText)	# recipient-country/text()
    recipient_country__code = Column(UnicodeText)	# recipient-country/@code
    recipient_country__percentage = Column(Float)	# recipient-country/@percentage
    recipient_country__lang = Column(UnicodeText)	# recipient-country/@xml:lang
    recipient_region__text = Column(UnicodeText)	# recipient-region/text()
    recipient_region__code = Column(UnicodeText)	# recipient-region/@code
    recipient_region__percentage = Column(Float)	# recipient-region/@percentage
    recipient_region__lang = Column(UnicodeText)	# recipient-region/@xml:lang
    collaboration_type__text = Column(UnicodeText)	# collaboration-type/text()
    collaboration_type__code = Column(UnicodeText)	# collaboration-type/@code
    collaboration_type__lang = Column(UnicodeText)	# collaboration-type/@xml:lang
    default_flow_type__text = Column(UnicodeText)	# default-flow-type/text()
    default_flow_type__code = Column(UnicodeText)	# default-flow-type/@code
    default_flow_type__lang = Column(UnicodeText)	# default-flow-type/@xml:lang
    default_aid_type__text = Column(UnicodeText)	# default-aid-type/text()
    default_aid_type__code = Column(UnicodeText)	# default-aid-type/@code
    default_aid_type__lang = Column(UnicodeText)	# default-aid-type/@xml:lang
    default_finance_type__text = Column(UnicodeText)	# default-finance-type/text()
    default_finance_type__code = Column(UnicodeText)	# default-finance-type/@code
    default_finance_type__lang = Column(UnicodeText)	# default-finance-type/@xml:lang
    iati_identifier__text = Column(UnicodeText)	# iati-identifier/text()
    other_identifier__text = Column(UnicodeText)	# other-identifier/text()
    other_identifier__owner_ref = Column(UnicodeText)	# other-identifier/@owner-ref
    other_identifier__owner_name = Column(UnicodeText)	# other-identifier/@owner-name
    title__text = Column(UnicodeText)	# title/text()
    title__lang = Column(UnicodeText)	# title/@xml:lang
    description__text = Column(UnicodeText)	# description/text()
    description__type = Column(UnicodeText)	# description/@type
    description__lang = Column(UnicodeText)	# description/@xml:lang
    activity_status__text = Column(UnicodeText)	# activity-status/text()
    activity_status__code = Column(UnicodeText)	# activity-status/@code
    activity_status__lang = Column(UnicodeText)	# activity-status/@xml:lang
    default_tied_status__text = Column(UnicodeText)	# default-tied-status/text()
    default_tied_status__code = Column(UnicodeText)	# default-tied-status/@code
    default_tied_status__lang = Column(UnicodeText)	# default-tied-status/@xml:lang
    policy_marker__text = Column(UnicodeText)	# policy-marker/text()
    policy_marker__code = Column(UnicodeText)	# policy-marker/@code
    policy_marker__vocabulary = Column(UnicodeText)	# policy-marker/@vocabulary
    policy_marker__significance = Column(UnicodeText)	# policy-marker/@significance
    policy_marker__lang = Column(UnicodeText)	# policy-marker/@xml:lang
    location__percentage = Column(Float)	# location/@percentage
    location__location_type__text = Column(UnicodeText)	# location/location-type/text()
    location__location_type__code = Column(UnicodeText)	# location/location-type/@code
    location__location_type__lang = Column(UnicodeText)	# location/location-type/@xml:lang
    location__name__text = Column(UnicodeText)	# location/name/text()
    location__name__lang = Column(UnicodeText)	# location/name/@xml:lang
    location__description__text = Column(UnicodeText)	# location/description/text()
    location__description__lang = Column(UnicodeText)	# location/description/@xml:lang
    location__administrative__text = Column(UnicodeText)	# location/administrative/text()
    location__administrative__country = Column(UnicodeText)	# location/administrative/@country
    location__administrative__adm1 = Column(UnicodeText)	# location/administrative/@adm1
    location__administrative__adm2 = Column(UnicodeText)	# location/administrative/@adm2
    location__coordinates__latitude = Column(Float)	# location/coordinates/@latitude
    location__coordinates__longitude = Column(Float)	# location/coordinates/@longitude
    location__coordinates__precision = Column(UnicodeText)	# location/coordinates/@precision
    location__gazetteer_entry__text = Column(UnicodeText)	# location/gazetteer-entry/text()
    location__gazetteer_entry__gazetteer_ref = Column(UnicodeText)	# location/gazetteer-entry/@gazetteer-ref
    result__type = Column(UnicodeText)	# result/@type
    result__aggregation_status = Column(Boolean)	# result/@aggregation-status
    result__title__text = Column(UnicodeText)	# result/title/text()
    result__title__lang = Column(UnicodeText)	# result/title/@xml:lang
    result__description__text = Column(UnicodeText)	# result/description/text()
    result__description__type = Column(UnicodeText)	# result/description/@type
    result__description__lang = Column(UnicodeText)	# result/description/@xml:lang
    result__indicator__measure = Column(UnicodeText)	# result/indicator/@measure
    result__indicator__ascending = Column(Boolean)	# result/indicator/@ascending
    result__indicator__title__text = Column(UnicodeText)	# result/indicator/title/text()
    result__indicator__title__lang = Column(UnicodeText)	# result/indicator/title/@xml:lang
    result__indicator__description__text = Column(UnicodeText)	# result/indicator/description/text()
    result__indicator__description__type = Column(UnicodeText)	# result/indicator/description/@type
    result__indicator__description__lang = Column(UnicodeText)	# result/indicator/description/@xml:lang
    result__indicator__baseline__year = Column(Float)	# result/indicator/baseline/@year
    result__indicator__baseline__value = Column(UnicodeText)	# result/indicator/baseline/@value
    result__indicator__baseline__comment__text = Column(UnicodeText)	# result/indicator/baseline/comment/text()
    result__indicator__baseline__comment__lang = Column(UnicodeText)	# result/indicator/baseline/comment/@xml:lang
    result__indicator__period__period_start__text = Column(UnicodeText)	# result/indicator/period/period-start/text()
    result__indicator__period__period_start__iso_date = Column(DateTime)	# result/indicator/period/period-start/@iso-date
    result__indicator__period__period_end__text = Column(UnicodeText)	# result/indicator/period/period-end/text()
    result__indicator__period__period_end__iso_date = Column(DateTime)	# result/indicator/period/period-end/@iso-date
    result__indicator__period__target__value = Column(UnicodeText)	# result/indicator/period/target/@value
    result__indicator__period__target__comment__text = Column(UnicodeText)	# result/indicator/period/target/comment/text()
    result__indicator__period__target__comment__lang = Column(UnicodeText)	# result/indicator/period/target/comment/@xml:lang
    result__indicator__period__actual__value = Column(UnicodeText)	# result/indicator/period/actual/@value
    result__indicator__period__actual__comment__text = Column(UnicodeText)	# result/indicator/period/actual/comment/text()
    result__indicator__period__actual__comment__lang = Column(UnicodeText)	# result/indicator/period/actual/comment/@xml:lang
    conditions__attached = Column(Boolean)	# conditions/@attached
    conditions__condition__text = Column(UnicodeText)	# conditions/condition/text()
    conditions__condition__type = Column(UnicodeText)	# conditions/condition/@type
    budget__type = Column(UnicodeText)	# budget/@type
    budget__period_start__text = Column(UnicodeText)	# budget/period-start/text()
    budget__period_start__iso_date = Column(DateTime)	# budget/period-start/@iso-date
    budget__period_end__text = Column(UnicodeText)	# budget/period-end/text()
    budget__period_end__iso_date = Column(DateTime)	# budget/period-end/@iso-date
    budget__value__text = Column(Float)	# budget/value/text()
    budget__value__currency = Column(UnicodeText)	# budget/value/@currency
    budget__value__value_date = Column(DateTime)	# budget/value/@value-date
    planned_disbursement__updated = Column(UnicodeText)	# planned-disbursement/@updated
    planned_disbursement__period_start__text = Column(UnicodeText)	# planned-disbursement/period-start/text()
    planned_disbursement__period_start__iso_date = Column(DateTime)	# planned-disbursement/period-start/@iso-date
    planned_disbursement__period_end__text = Column(UnicodeText)	# planned-disbursement/period-end/text()
    planned_disbursement__period_end__iso_date = Column(DateTime)	# planned-disbursement/period-end/@iso-date
    planned_disbursement__value__text = Column(Float)	# planned-disbursement/value/text()
    planned_disbursement__value__currency = Column(UnicodeText)	# planned-disbursement/value/@currency
    planned_disbursement__value__value_date = Column(DateTime)	# planned-disbursement/value/@value-date
    related_activity__text = Column(UnicodeText)	# related-activity/text()
    related_activity__ref = Column(UnicodeText)	# related-activity/@ref
    related_activity__type = Column(UnicodeText)	# related-activity/@type
    related_activity__lang = Column(UnicodeText)	# related-activity/@xml:lang
    document_link__url = Column(UnicodeText)	# document-link/@url
    document_link__format = Column(UnicodeText)	# document-link/@format
    document_link__title__text = Column(UnicodeText)	# document-link/title/text()
    document_link__title__lang = Column(UnicodeText)	# document-link/title/@xml:lang
    document_link__category__text = Column(UnicodeText)	# document-link/category/text()
    document_link__category__code = Column(UnicodeText)	# document-link/category/@code
    document_link__category__lang = Column(UnicodeText)	# document-link/category/@xml:lang
    document_link__language__text = Column(UnicodeText)	# document-link/language/text()
    document_link__language__code = Column(UnicodeText)	# document-link/language/@code
    document_link__language__lang = Column(UnicodeText)	# document-link/language/@xml:lang
    legacy_data__text = Column(UnicodeText)	# legacy-data/text()
    legacy_data__name = Column(UnicodeText)	# legacy-data/@name
    legacy_data__value = Column(UnicodeText)	# legacy-data/@value
    legacy_data__iati_equivalent = Column(UnicodeText)	# legacy-data/@iati-equivalent
    @classmethod
    def _parse_xml(cls,logger,xml):
        data = {}
        data['version'] = _nav(logger, xml, [], attrib='version', parser=_parse_float)
        data['last_updated_datetime'] = _nav(logger, xml, [], attrib='last-updated-datetime', parser=_parse_datetime)
        data['lang'] = _nav(logger, xml, [], attrib='xml:lang')
        data['default_currency'] = _nav(logger, xml, [], attrib='default-currency')
        data['hierarchy'] = _nav(logger, xml, [], attrib='hierarchy', parser=_parse_float)
        data['linked_data_uri'] = _nav(logger, xml, [], attrib='linked-data-uri')
        data['activity_website__text'] = _nav(logger, xml, ['activity-website'], text=True)
        data['reporting_org__text'] = _nav(logger, xml, ['reporting-org'], text=True)
        data['reporting_org__ref'] = _nav(logger, xml, ['reporting-org'], attrib='ref')
        data['reporting_org__type'] = _nav(logger, xml, ['reporting-org'], attrib='type')
        data['reporting_org__lang'] = _nav(logger, xml, ['reporting-org'], attrib='xml:lang')
        data['recipient_country__text'] = _nav(logger, xml, ['recipient-country'], text=True)
        data['recipient_country__code'] = _nav(logger, xml, ['recipient-country'], attrib='code')
        data['recipient_country__percentage'] = _nav(logger, xml, ['recipient-country'], attrib='percentage', parser=_parse_float)
        data['recipient_country__lang'] = _nav(logger, xml, ['recipient-country'], attrib='xml:lang')
        data['recipient_region__text'] = _nav(logger, xml, ['recipient-region'], text=True)
        data['recipient_region__code'] = _nav(logger, xml, ['recipient-region'], attrib='code')
        data['recipient_region__percentage'] = _nav(logger, xml, ['recipient-region'], attrib='percentage', parser=_parse_float)
        data['recipient_region__lang'] = _nav(logger, xml, ['recipient-region'], attrib='xml:lang')
        data['collaboration_type__text'] = _nav(logger, xml, ['collaboration-type'], text=True)
        data['collaboration_type__code'] = _nav(logger, xml, ['collaboration-type'], attrib='code')
        data['collaboration_type__lang'] = _nav(logger, xml, ['collaboration-type'], attrib='xml:lang')
        data['default_flow_type__text'] = _nav(logger, xml, ['default-flow-type'], text=True)
        data['default_flow_type__code'] = _nav(logger, xml, ['default-flow-type'], attrib='code')
        data['default_flow_type__lang'] = _nav(logger, xml, ['default-flow-type'], attrib='xml:lang')
        data['default_aid_type__text'] = _nav(logger, xml, ['default-aid-type'], text=True)
        data['default_aid_type__code'] = _nav(logger, xml, ['default-aid-type'], attrib='code')
        data['default_aid_type__lang'] = _nav(logger, xml, ['default-aid-type'], attrib='xml:lang')
        data['default_finance_type__text'] = _nav(logger, xml, ['default-finance-type'], text=True)
        data['default_finance_type__code'] = _nav(logger, xml, ['default-finance-type'], attrib='code')
        data['default_finance_type__lang'] = _nav(logger, xml, ['default-finance-type'], attrib='xml:lang')
        data['iati_identifier__text'] = _nav(logger, xml, ['iati-identifier'], text=True)
        data['other_identifier__text'] = _nav(logger, xml, ['other-identifier'], text=True)
        data['other_identifier__owner_ref'] = _nav(logger, xml, ['other-identifier'], attrib='owner-ref')
        data['other_identifier__owner_name'] = _nav(logger, xml, ['other-identifier'], attrib='owner-name')
        data['title__text'] = _nav(logger, xml, ['title'], text=True)
        data['title__lang'] = _nav(logger, xml, ['title'], attrib='xml:lang')
        data['description__text'] = _nav(logger, xml, ['description'], text=True)
        data['description__type'] = _nav(logger, xml, ['description'], attrib='type')
        data['description__lang'] = _nav(logger, xml, ['description'], attrib='xml:lang')
        data['activity_status__text'] = _nav(logger, xml, ['activity-status'], text=True)
        data['activity_status__code'] = _nav(logger, xml, ['activity-status'], attrib='code')
        data['activity_status__lang'] = _nav(logger, xml, ['activity-status'], attrib='xml:lang')
        data['default_tied_status__text'] = _nav(logger, xml, ['default-tied-status'], text=True)
        data['default_tied_status__code'] = _nav(logger, xml, ['default-tied-status'], attrib='code')
        data['default_tied_status__lang'] = _nav(logger, xml, ['default-tied-status'], attrib='xml:lang')
        data['policy_marker__text'] = _nav(logger, xml, ['policy-marker'], text=True)
        data['policy_marker__code'] = _nav(logger, xml, ['policy-marker'], attrib='code')
        data['policy_marker__vocabulary'] = _nav(logger, xml, ['policy-marker'], attrib='vocabulary')
        data['policy_marker__significance'] = _nav(logger, xml, ['policy-marker'], attrib='significance')
        data['policy_marker__lang'] = _nav(logger, xml, ['policy-marker'], attrib='xml:lang')
        data['location__percentage'] = _nav(logger, xml, ['location'], attrib='percentage', parser=_parse_float)
        data['location__location_type__text'] = _nav(logger, xml, ['location','location-type'], text=True)
        data['location__location_type__code'] = _nav(logger, xml, ['location','location-type'], attrib='code')
        data['location__location_type__lang'] = _nav(logger, xml, ['location','location-type'], attrib='xml:lang')
        data['location__name__text'] = _nav(logger, xml, ['location','name'], text=True)
        data['location__name__lang'] = _nav(logger, xml, ['location','name'], attrib='xml:lang')
        data['location__description__text'] = _nav(logger, xml, ['location','description'], text=True)
        data['location__description__lang'] = _nav(logger, xml, ['location','description'], attrib='xml:lang')
        data['location__administrative__text'] = _nav(logger, xml, ['location','administrative'], text=True)
        data['location__administrative__country'] = _nav(logger, xml, ['location','administrative'], attrib='country')
        data['location__administrative__adm1'] = _nav(logger, xml, ['location','administrative'], attrib='adm1')
        data['location__administrative__adm2'] = _nav(logger, xml, ['location','administrative'], attrib='adm2')
        data['location__coordinates__latitude'] = _nav(logger, xml, ['location','coordinates'], attrib='latitude', parser=_parse_float)
        data['location__coordinates__longitude'] = _nav(logger, xml, ['location','coordinates'], attrib='longitude', parser=_parse_float)
        data['location__coordinates__precision'] = _nav(logger, xml, ['location','coordinates'], attrib='precision')
        data['location__gazetteer_entry__text'] = _nav(logger, xml, ['location','gazetteer-entry'], text=True)
        data['location__gazetteer_entry__gazetteer_ref'] = _nav(logger, xml, ['location','gazetteer-entry'], attrib='gazetteer-ref')
        data['result__type'] = _nav(logger, xml, ['result'], attrib='type')
        data['result__aggregation_status'] = _nav(logger, xml, ['result'], attrib='aggregation-status', parser=_parse_boolean)
        data['result__title__text'] = _nav(logger, xml, ['result','title'], text=True)
        data['result__title__lang'] = _nav(logger, xml, ['result','title'], attrib='xml:lang')
        data['result__description__text'] = _nav(logger, xml, ['result','description'], text=True)
        data['result__description__type'] = _nav(logger, xml, ['result','description'], attrib='type')
        data['result__description__lang'] = _nav(logger, xml, ['result','description'], attrib='xml:lang')
        data['result__indicator__measure'] = _nav(logger, xml, ['result','indicator'], attrib='measure')
        data['result__indicator__ascending'] = _nav(logger, xml, ['result','indicator'], attrib='ascending', parser=_parse_boolean)
        data['result__indicator__title__text'] = _nav(logger, xml, ['result','indicator','title'], text=True)
        data['result__indicator__title__lang'] = _nav(logger, xml, ['result','indicator','title'], attrib='xml:lang')
        data['result__indicator__description__text'] = _nav(logger, xml, ['result','indicator','description'], text=True)
        data['result__indicator__description__type'] = _nav(logger, xml, ['result','indicator','description'], attrib='type')
        data['result__indicator__description__lang'] = _nav(logger, xml, ['result','indicator','description'], attrib='xml:lang')
        data['result__indicator__baseline__year'] = _nav(logger, xml, ['result','indicator','baseline'], attrib='year', parser=_parse_float)
        data['result__indicator__baseline__value'] = _nav(logger, xml, ['result','indicator','baseline'], attrib='value')
        data['result__indicator__baseline__comment__text'] = _nav(logger, xml, ['result','indicator','baseline','comment'], text=True)
        data['result__indicator__baseline__comment__lang'] = _nav(logger, xml, ['result','indicator','baseline','comment'], attrib='xml:lang')
        data['result__indicator__period__period_start__text'] = _nav(logger, xml, ['result','indicator','period','period-start'], text=True)
        data['result__indicator__period__period_start__iso_date'] = _nav(logger, xml, ['result','indicator','period','period-start'], attrib='iso-date', parser=_parse_datetime)
        data['result__indicator__period__period_end__text'] = _nav(logger, xml, ['result','indicator','period','period-end'], text=True)
        data['result__indicator__period__period_end__iso_date'] = _nav(logger, xml, ['result','indicator','period','period-end'], attrib='iso-date', parser=_parse_datetime)
        data['result__indicator__period__target__value'] = _nav(logger, xml, ['result','indicator','period','target'], attrib='value')
        data['result__indicator__period__target__comment__text'] = _nav(logger, xml, ['result','indicator','period','target','comment'], text=True)
        data['result__indicator__period__target__comment__lang'] = _nav(logger, xml, ['result','indicator','period','target','comment'], attrib='xml:lang')
        data['result__indicator__period__actual__value'] = _nav(logger, xml, ['result','indicator','period','actual'], attrib='value')
        data['result__indicator__period__actual__comment__text'] = _nav(logger, xml, ['result','indicator','period','actual','comment'], text=True)
        data['result__indicator__period__actual__comment__lang'] = _nav(logger, xml, ['result','indicator','period','actual','comment'], attrib='xml:lang')
        data['conditions__attached'] = _nav(logger, xml, ['conditions'], attrib='attached', parser=_parse_boolean)
        data['conditions__condition__text'] = _nav(logger, xml, ['conditions','condition'], text=True)
        data['conditions__condition__type'] = _nav(logger, xml, ['conditions','condition'], attrib='type')
        data['budget__type'] = _nav(logger, xml, ['budget'], attrib='type')
        data['budget__period_start__text'] = _nav(logger, xml, ['budget','period-start'], text=True)
        data['budget__period_start__iso_date'] = _nav(logger, xml, ['budget','period-start'], attrib='iso-date', parser=_parse_datetime)
        data['budget__period_end__text'] = _nav(logger, xml, ['budget','period-end'], text=True)
        data['budget__period_end__iso_date'] = _nav(logger, xml, ['budget','period-end'], attrib='iso-date', parser=_parse_datetime)
        data['budget__value__text'] = _nav(logger, xml, ['budget','value'], text=True, parser=_parse_float)
        data['budget__value__currency'] = _nav(logger, xml, ['budget','value'], attrib='currency')
        data['budget__value__value_date'] = _nav(logger, xml, ['budget','value'], attrib='value-date', parser=_parse_datetime)
        data['planned_disbursement__updated'] = _nav(logger, xml, ['planned-disbursement'], attrib='updated')
        data['planned_disbursement__period_start__text'] = _nav(logger, xml, ['planned-disbursement','period-start'], text=True)
        data['planned_disbursement__period_start__iso_date'] = _nav(logger, xml, ['planned-disbursement','period-start'], attrib='iso-date', parser=_parse_datetime)
        data['planned_disbursement__period_end__text'] = _nav(logger, xml, ['planned-disbursement','period-end'], text=True)
        data['planned_disbursement__period_end__iso_date'] = _nav(logger, xml, ['planned-disbursement','period-end'], attrib='iso-date', parser=_parse_datetime)
        data['planned_disbursement__value__text'] = _nav(logger, xml, ['planned-disbursement','value'], text=True, parser=_parse_float)
        data['planned_disbursement__value__currency'] = _nav(logger, xml, ['planned-disbursement','value'], attrib='currency')
        data['planned_disbursement__value__value_date'] = _nav(logger, xml, ['planned-disbursement','value'], attrib='value-date', parser=_parse_datetime)
        data['related_activity__text'] = _nav(logger, xml, ['related-activity'], text=True)
        data['related_activity__ref'] = _nav(logger, xml, ['related-activity'], attrib='ref')
        data['related_activity__type'] = _nav(logger, xml, ['related-activity'], attrib='type')
        data['related_activity__lang'] = _nav(logger, xml, ['related-activity'], attrib='xml:lang')
        data['document_link__url'] = _nav(logger, xml, ['document-link'], attrib='url')
        data['document_link__format'] = _nav(logger, xml, ['document-link'], attrib='format')
        data['document_link__title__text'] = _nav(logger, xml, ['document-link','title'], text=True)
        data['document_link__title__lang'] = _nav(logger, xml, ['document-link','title'], attrib='xml:lang')
        data['document_link__category__text'] = _nav(logger, xml, ['document-link','category'], text=True)
        data['document_link__category__code'] = _nav(logger, xml, ['document-link','category'], attrib='code')
        data['document_link__category__lang'] = _nav(logger, xml, ['document-link','category'], attrib='xml:lang')
        data['document_link__language__text'] = _nav(logger, xml, ['document-link','language'], text=True)
        data['document_link__language__code'] = _nav(logger, xml, ['document-link','language'], attrib='code')
        data['document_link__language__lang'] = _nav(logger, xml, ['document-link','language'], attrib='xml:lang')
        data['legacy_data__text'] = _nav(logger, xml, ['legacy-data'], text=True)
        data['legacy_data__name'] = _nav(logger, xml, ['legacy-data'], attrib='name')
        data['legacy_data__value'] = _nav(logger, xml, ['legacy-data'], attrib='value')
        data['legacy_data__iati_equivalent'] = _nav(logger, xml, ['legacy-data'], attrib='iati-equivalent')
        out = Activity(**data)
        for child_xml in xml.findall('transaction'):
            out.transaction.append( Transaction._parse_xml(logger,child_xml) )
        for child_xml in xml.findall('sector'):
            out.sector.append( Sector._parse_xml(logger,child_xml) )
        for child_xml in xml.findall('participating-org'):
            out.participatingorg.append( ParticipatingOrg._parse_xml(logger,child_xml) )
        for child_xml in xml.findall('contact-info'):
            out.contactinfo.append( ContactInfo._parse_xml(logger,child_xml) )
        for child_xml in xml.findall('activity-date'):
            out.activitydate.append( ActivityDate._parse_xml(logger,child_xml) )
        return out

class Transaction(Base):
    __tablename__ = 'transaction'
    id = Column(Integer, primary_key=True)
    transaction_value = relationship("TransactionValue",cascade="all")
    transaction_description = relationship("TransactionDescription",cascade="all")
    transaction_type = relationship("TransactionType",cascade="all")
    transaction_provider_org = relationship("TransactionProviderOrg",cascade="all")
    transaction_receiver_org = relationship("TransactionReceiverOrg",cascade="all")
    transaction_date = relationship("TransactionDate",cascade="all")
    transaction_flow_type = relationship("TransactionFlowType",cascade="all")
    transaction_aid_type = relationship("TransactionAidType",cascade="all")
    transaction_finance_type = relationship("TransactionFinanceType",cascade="all")
    transaction_tied_status = relationship("TransactionTiedStatus",cascade="all")
    transaction_disbursement_channel = relationship("TransactionDisbursementChannel",cascade="all")
    parent_id = Column(Integer, ForeignKey('activity.id'), nullable=False)
    ref = Column(UnicodeText)	# @ref
    @classmethod
    def _parse_xml(cls,logger,xml):
        data = {}
        data['ref'] = _nav(logger, xml, [], attrib='ref')
        out = Transaction(**data)
        for child_xml in xml.findall('value'):
            out.transaction_value.append( TransactionValue._parse_xml(logger,child_xml) )
        for child_xml in xml.findall('description'):
            out.transaction_description.append( TransactionDescription._parse_xml(logger,child_xml) )
        for child_xml in xml.findall('transaction-type'):
            out.transaction_type.append( TransactionType._parse_xml(logger,child_xml) )
        for child_xml in xml.findall('provider-org'):
            out.transaction_provider_org.append( TransactionProviderOrg._parse_xml(logger,child_xml) )
        for child_xml in xml.findall('receiver-org'):
            out.transaction_receiver_org.append( TransactionReceiverOrg._parse_xml(logger,child_xml) )
        for child_xml in xml.findall('transaction-date'):
            out.transaction_date.append( TransactionDate._parse_xml(logger,child_xml) )
        for child_xml in xml.findall('flow-type'):
            out.transaction_flow_type.append( TransactionFlowType._parse_xml(logger,child_xml) )
        for child_xml in xml.findall('aid-type'):
            out.transaction_aid_type.append( TransactionAidType._parse_xml(logger,child_xml) )
        for child_xml in xml.findall('finance-type'):
            out.transaction_finance_type.append( TransactionFinanceType._parse_xml(logger,child_xml) )
        for child_xml in xml.findall('tied-status'):
            out.transaction_tied_status.append( TransactionTiedStatus._parse_xml(logger,child_xml) )
        for child_xml in xml.findall('disbursement-channel'):
            out.transaction_disbursement_channel.append( TransactionDisbursementChannel._parse_xml(logger,child_xml) )
        return out

class TransactionValue(Base):
    __tablename__ = 'transaction_value'
    id = Column(Integer, primary_key=True)
    parent_id = Column(Integer, ForeignKey('transaction.id'), nullable=False)
    text = Column(Float)	# text()
    currency = Column(UnicodeText)	# @currency
    value_date = Column(DateTime)	# @value-date
    @classmethod
    def _parse_xml(cls,logger,xml):
        data = {}
        data['text'] = _nav(logger, xml, [], text=True, parser=_parse_float)
        data['currency'] = _nav(logger, xml, [], attrib='currency')
        data['value_date'] = _nav(logger, xml, [], attrib='value-date', parser=_parse_datetime)
        out = TransactionValue(**data)
        return out

class TransactionDescription(Base):
    __tablename__ = 'transaction_description'
    id = Column(Integer, primary_key=True)
    parent_id = Column(Integer, ForeignKey('transaction.id'), nullable=False)
    text = Column(UnicodeText)	# text()
    lang = Column(UnicodeText)	# @xml:lang
    @classmethod
    def _parse_xml(cls,logger,xml):
        data = {}
        data['text'] = _nav(logger, xml, [], text=True)
        data['lang'] = _nav(logger, xml, [], attrib='xml:lang')
        out = TransactionDescription(**data)
        return out

class TransactionType(Base):
    __tablename__ = 'transaction_type'
    id = Column(Integer, primary_key=True)
    parent_id = Column(Integer, ForeignKey('transaction.id'), nullable=False)
    text = Column(UnicodeText)	# text()
    code = Column(UnicodeText)	# @code
    lang = Column(UnicodeText)	# @xml:lang
    @classmethod
    def _parse_xml(cls,logger,xml):
        data = {}
        data['text'] = _nav(logger, xml, [], text=True)
        data['code'] = _nav(logger, xml, [], attrib='code')
        data['lang'] = _nav(logger, xml, [], attrib='xml:lang')
        out = TransactionType(**data)
        return out

class TransactionProviderOrg(Base):
    __tablename__ = 'transaction_provider_org'
    id = Column(Integer, primary_key=True)
    parent_id = Column(Integer, ForeignKey('transaction.id'), nullable=False)
    text = Column(UnicodeText)	# text()
    ref = Column(UnicodeText)	# @ref
    provider_activity_id = Column(UnicodeText)	# @provider-activity-id
    @classmethod
    def _parse_xml(cls,logger,xml):
        data = {}
        data['text'] = _nav(logger, xml, [], text=True)
        data['ref'] = _nav(logger, xml, [], attrib='ref')
        data['provider_activity_id'] = _nav(logger, xml, [], attrib='provider-activity-id')
        out = TransactionProviderOrg(**data)
        return out

class TransactionReceiverOrg(Base):
    __tablename__ = 'transaction_receiver_org'
    id = Column(Integer, primary_key=True)
    parent_id = Column(Integer, ForeignKey('transaction.id'), nullable=False)
    text = Column(UnicodeText)	# text()
    ref = Column(UnicodeText)	# @ref
    receiver_activity_id = Column(UnicodeText)	# @receiver-activity-id
    @classmethod
    def _parse_xml(cls,logger,xml):
        data = {}
        data['text'] = _nav(logger, xml, [], text=True)
        data['ref'] = _nav(logger, xml, [], attrib='ref')
        data['receiver_activity_id'] = _nav(logger, xml, [], attrib='receiver-activity-id')
        out = TransactionReceiverOrg(**data)
        return out

class TransactionDate(Base):
    __tablename__ = 'transaction_date'
    id = Column(Integer, primary_key=True)
    parent_id = Column(Integer, ForeignKey('transaction.id'), nullable=False)
    text = Column(UnicodeText)	# text()
    iso_date = Column(DateTime)	# @iso-date
    @classmethod
    def _parse_xml(cls,logger,xml):
        data = {}
        data['text'] = _nav(logger, xml, [], text=True)
        data['iso_date'] = _nav(logger, xml, [], attrib='iso-date', parser=_parse_datetime)
        out = TransactionDate(**data)
        return out

class TransactionFlowType(Base):
    __tablename__ = 'transaction_flow_type'
    id = Column(Integer, primary_key=True)
    parent_id = Column(Integer, ForeignKey('transaction.id'), nullable=False)
    text = Column(UnicodeText)	# text()
    code = Column(UnicodeText)	# @code
    lang = Column(UnicodeText)	# @xml:lang
    @classmethod
    def _parse_xml(cls,logger,xml):
        data = {}
        data['text'] = _nav(logger, xml, [], text=True)
        data['code'] = _nav(logger, xml, [], attrib='code')
        data['lang'] = _nav(logger, xml, [], attrib='xml:lang')
        out = TransactionFlowType(**data)
        return out

class TransactionAidType(Base):
    __tablename__ = 'transaction_aid_type'
    id = Column(Integer, primary_key=True)
    parent_id = Column(Integer, ForeignKey('transaction.id'), nullable=False)
    text = Column(UnicodeText)	# text()
    code = Column(UnicodeText)	# @code
    lang = Column(UnicodeText)	# @xml:lang
    @classmethod
    def _parse_xml(cls,logger,xml):
        data = {}
        data['text'] = _nav(logger, xml, [], text=True)
        data['code'] = _nav(logger, xml, [], attrib='code')
        data['lang'] = _nav(logger, xml, [], attrib='xml:lang')
        out = TransactionAidType(**data)
        return out

class TransactionFinanceType(Base):
    __tablename__ = 'transaction_finance_type'
    id = Column(Integer, primary_key=True)
    parent_id = Column(Integer, ForeignKey('transaction.id'), nullable=False)
    text = Column(UnicodeText)	# text()
    code = Column(UnicodeText)	# @code
    lang = Column(UnicodeText)	# @xml:lang
    @classmethod
    def _parse_xml(cls,logger,xml):
        data = {}
        data['text'] = _nav(logger, xml, [], text=True)
        data['code'] = _nav(logger, xml, [], attrib='code')
        data['lang'] = _nav(logger, xml, [], attrib='xml:lang')
        out = TransactionFinanceType(**data)
        return out

class TransactionTiedStatus(Base):
    __tablename__ = 'transaction_tied_status'
    id = Column(Integer, primary_key=True)
    parent_id = Column(Integer, ForeignKey('transaction.id'), nullable=False)
    text = Column(UnicodeText)	# text()
    code = Column(UnicodeText)	# @code
    lang = Column(UnicodeText)	# @xml:lang
    @classmethod
    def _parse_xml(cls,logger,xml):
        data = {}
        data['text'] = _nav(logger, xml, [], text=True)
        data['code'] = _nav(logger, xml, [], attrib='code')
        data['lang'] = _nav(logger, xml, [], attrib='xml:lang')
        out = TransactionTiedStatus(**data)
        return out

class TransactionDisbursementChannel(Base):
    __tablename__ = 'transaction_disbursement_channel'
    id = Column(Integer, primary_key=True)
    parent_id = Column(Integer, ForeignKey('transaction.id'), nullable=False)
    text = Column(UnicodeText)	# text()
    code = Column(UnicodeText)	# @code
    lang = Column(UnicodeText)	# @xml:lang
    @classmethod
    def _parse_xml(cls,logger,xml):
        data = {}
        data['text'] = _nav(logger, xml, [], text=True)
        data['code'] = _nav(logger, xml, [], attrib='code')
        data['lang'] = _nav(logger, xml, [], attrib='xml:lang')
        out = TransactionDisbursementChannel(**data)
        return out

class Sector(Base):
    __tablename__ = 'sector'
    id = Column(Integer, primary_key=True)
    parent_id = Column(Integer, ForeignKey('activity.id'), nullable=False)
    text = Column(UnicodeText)	# text()
    code = Column(Integer)	# @code
    vocabulary = Column(UnicodeText)	# @vocabulary
    percentage = Column(Float)	# @percentage
    lang = Column(UnicodeText)	# @xml:lang
    @classmethod
    def _parse_xml(cls,logger,xml):
        data = {}
        data['text'] = _nav(logger, xml, [], text=True)
        data['code'] = _nav(logger, xml, [], attrib='code', parser=_parse_int)
        data['vocabulary'] = _nav(logger, xml, [], attrib='vocabulary')
        data['percentage'] = _nav(logger, xml, [], attrib='percentage', parser=_parse_float)
        data['lang'] = _nav(logger, xml, [], attrib='xml:lang')
        out = Sector(**data)
        return out

class ActivityDate(Base):
    __tablename__ = 'activitydate'
    id = Column(Integer, primary_key=True)
    parent_id = Column(Integer, ForeignKey('activity.id'), nullable=False)
    text = Column(UnicodeText)	# text()
    type = Column(UnicodeText)	# @type
    iso_date = Column(DateTime)	# @iso-date
    lang = Column(UnicodeText)	# @xml:lang
    @classmethod
    def _parse_xml(cls,logger,xml):
        data = {}
        data['text'] = _nav(logger, xml, [], text=True)
        data['type'] = _nav(logger, xml, [], attrib='type')
        data['iso_date'] = _nav(logger, xml, [], attrib='iso-date', parser=_parse_datetime)
        data['lang'] = _nav(logger, xml, [], attrib='xml:lang')
        out = ActivityDate(**data)
        return out

class ContactInfo(Base):
    __tablename__ = 'contactinfo'
    id = Column(Integer, primary_key=True)
    contactinfo_organisation = relationship("ContactInfoOrganisation",cascade="all")
    contactinfo_person = relationship("ContactInfoPerson",cascade="all")
    contactinfo_telephone = relationship("ContactInfoTelephone",cascade="all")
    contactinfo_email = relationship("ContactInfoEmail",cascade="all")
    contactinfo_mail = relationship("ContactInfoMail",cascade="all")
    parent_id = Column(Integer, ForeignKey('activity.id'), nullable=False)
    @classmethod
    def _parse_xml(cls,logger,xml):
        data = {}
        out = ContactInfo(**data)
        for child_xml in xml.findall('organisation'):
            out.contactinfo_organisation.append( ContactInfoOrganisation._parse_xml(logger,child_xml) )
        for child_xml in xml.findall('person-name'):
            out.contactinfo_person.append( ContactInfoPerson._parse_xml(logger,child_xml) )
        for child_xml in xml.findall('telephone'):
            out.contactinfo_telephone.append( ContactInfoTelephone._parse_xml(logger,child_xml) )
        for child_xml in xml.findall('email'):
            out.contactinfo_email.append( ContactInfoEmail._parse_xml(logger,child_xml) )
        for child_xml in xml.findall('mailing-address'):
            out.contactinfo_mail.append( ContactInfoMail._parse_xml(logger,child_xml) )
        return out

class ContactInfoOrganisation(Base):
    __tablename__ = 'contactinfo_organisation'
    id = Column(Integer, primary_key=True)
    parent_id = Column(Integer, ForeignKey('contactinfo.id'), nullable=False)
    text = Column(UnicodeText)	# text()
    @classmethod
    def _parse_xml(cls,logger,xml):
        data = {}
        data['text'] = _nav(logger, xml, [], text=True)
        out = ContactInfoOrganisation(**data)
        return out

class ContactInfoPerson(Base):
    __tablename__ = 'contactinfo_person'
    id = Column(Integer, primary_key=True)
    parent_id = Column(Integer, ForeignKey('contactinfo.id'), nullable=False)
    text = Column(UnicodeText)	# text()
    @classmethod
    def _parse_xml(cls,logger,xml):
        data = {}
        data['text'] = _nav(logger, xml, [], text=True)
        out = ContactInfoPerson(**data)
        return out

class ContactInfoTelephone(Base):
    __tablename__ = 'contactinfo_telephone'
    id = Column(Integer, primary_key=True)
    parent_id = Column(Integer, ForeignKey('contactinfo.id'), nullable=False)
    text = Column(UnicodeText)	# text()
    @classmethod
    def _parse_xml(cls,logger,xml):
        data = {}
        data['text'] = _nav(logger, xml, [], text=True)
        out = ContactInfoTelephone(**data)
        return out

class ContactInfoEmail(Base):
    __tablename__ = 'contactinfo_email'
    id = Column(Integer, primary_key=True)
    parent_id = Column(Integer, ForeignKey('contactinfo.id'), nullable=False)
    text = Column(UnicodeText)	# text()
    @classmethod
    def _parse_xml(cls,logger,xml):
        data = {}
        data['text'] = _nav(logger, xml, [], text=True)
        out = ContactInfoEmail(**data)
        return out

class ContactInfoMail(Base):
    __tablename__ = 'contactinfo_mail'
    id = Column(Integer, primary_key=True)
    parent_id = Column(Integer, ForeignKey('contactinfo.id'), nullable=False)
    text = Column(UnicodeText)	# text()
    @classmethod
    def _parse_xml(cls,logger,xml):
        data = {}
        data['text'] = _nav(logger, xml, [], text=True)
        out = ContactInfoMail(**data)
        return out

class ParticipatingOrg(Base):
    __tablename__ = 'participatingorg'
    id = Column(Integer, primary_key=True)
    parent_id = Column(Integer, ForeignKey('activity.id'), nullable=False)
    text = Column(UnicodeText)	# text()
    ref = Column(UnicodeText)	# @ref
    type = Column(UnicodeText)	# @type
    role = Column(UnicodeText)	# @role
    lang = Column(UnicodeText)	# @xml:lang
    @classmethod
    def _parse_xml(cls,logger,xml):
        data = {}
        data['text'] = _nav(logger, xml, [], text=True)
        data['ref'] = _nav(logger, xml, [], attrib='ref')
        data['type'] = _nav(logger, xml, [], attrib='type')
        data['role'] = _nav(logger, xml, [], attrib='role')
        data['lang'] = _nav(logger, xml, [], attrib='xml:lang')
        out = ParticipatingOrg(**data)
        return out
